# Generated by Django 4.2.13 on 2024-06-26 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('preferred_name', models.CharField(blank=True, max_length=30)),
                ('default_role', models.CharField(choices=[('BARTENDER', 'Bartender'), ('BARBACK', 'Barback'), ('SECURITY', 'Security'), ('OTHER', 'Other')], max_length=30)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
