# Generated by Django 4.2.13 on 2024-06-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_employee_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
