# Generated by Django 4.2.13 on 2024-07-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField()),
                ('submitter', models.CharField(default='', max_length=30)),
                ('rev_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rev_hourly', models.JSONField()),
                ('rev_method', models.CharField(max_length=30)),
                ('cash_tips', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cc_tips', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_tips', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tips_paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tips_pull_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tips_pull_time', models.DateTimeField(blank=True)),
                ('worked_minutes', models.IntegerField(default=0)),
                ('bartender_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('barback_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('security_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Timecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('minutes_total', models.IntegerField(default=0)),
                ('minutes_hourly', models.JSONField()),
                ('earned_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('earned_hourly', models.JSONField()),
                ('tips_to_report', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
        ),
    ]
