# Generated by Django 4.2.13 on 2024-07-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tips_pull_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
