# Generated by Django 4.2.13 on 2024-07-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_tips_pull_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='submitter',
            new_name='submitter_name',
        ),
    ]
