# Generated by Django 4.2.13 on 2024-07-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_submitter_report_submitter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='submitter_pk',
            field=models.IntegerField(default=0),
        ),
    ]
