# Generated by Django 4.2.13 on 2024-07-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_timecard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='earned_tips',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
