# Generated by Django 4.2.13 on 2024-07-16 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_timecard_earned_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 1, 36, 32, 352973, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='timecard',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 1, 36, 32, 352568, tzinfo=datetime.timezone.utc)),
        ),
    ]
