# Generated by Django 4.2.13 on 2024-07-17 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_report_tips_diff_alter_timecard_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 0, 25, 27, 681745, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 0, 25, 27, 681446, tzinfo=datetime.timezone.utc)),
        ),
    ]
