# Generated by Django 4.2.13 on 2024-07-17 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_timecard_end_time_alter_timecard_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 23, 57, 15, 379732, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 23, 57, 15, 379445, tzinfo=datetime.timezone.utc)),
        ),
    ]
