# Generated by Django 4.2.13 on 2024-06-16 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('BARTENDER', 'Bartender'), ('BARBACK', 'Barback'), ('SECURITY', 'Security'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
