# Generated by Django 4.2.13 on 2024-06-16 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0003_employee_active_employee_created_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
