# Generated by Django 4.2.13 on 2024-06-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0004_delete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='role',
            new_name='default_role',
        ),
    ]
