# Generated by Django 4.2.13 on 2024-06-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0006_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
