# Generated by Django 4.2.13 on 2024-06-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0009_remove_employee_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
